package com.tvbox.android44.feature.settings;

import com.google.gson.Gson;
import com.tvbox.android44.data.local.SettingsRepository;

/** Phone-only model configuration. No stored credentials are inserted into the page. */
final class AiConfigPage {
    static String render(String token) {
        String providers = new Gson().toJson(SettingsRepository.AI_PROVIDERS);
        return "<!DOCTYPE html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\">"
                + "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
                + "<title>TVBox4.1+ · AI 配置</title>"
                + "<style>body{font-family:sans-serif;max-width:520px;margin:24px auto;padding:0 18px}"
                + "input,select,button{box-sizing:border-box;font-size:16px;padding:12px;width:100%}"
                + "button{margin-top:10px}input[type=checkbox]{width:auto}small{color:#666}"
                + "#status{white-space:pre-wrap;overflow-wrap:break-word}</style></head><body>"
                + "<h2>TVBox4.1+ · AI 配置</h2>"
                + "<form id=\"config\" method=\"POST\" action=\"/" + token + "\">"
                + "<p>提供方<select id=\"provider\" name=\"provider\"></select></p>"
                + "<p>默认 API 地址<input id=\"base\" readonly></p>"
                + "<small>使用普通中国区开放平台 Key，不适用于 Coding/Token Plan 套餐。</small>"
                + "<p>API Key<input id=\"key\" name=\"apiKey\" type=\"password\" autocomplete=\"new-password\""
                + " autocapitalize=\"none\" spellcheck=\"false\" placeholder=\"请输入所选提供方的 Key\" required></p>"
                + "<button id=\"fetch\" type=\"button\" disabled>获取模型列表</button>"
                + "<p id=\"status\" role=\"status\"></p>"
                + "<p>选择模型<select id=\"models\" disabled><option value=\"\">请先获取模型列表</option></select></p>"
                + "<p><label><input id=\"manualMode\" type=\"checkbox\"> 手动输入模型 ID（高级/兜底）</label></p>"
                + "<p id=\"manualBox\" hidden><input id=\"manual\" placeholder=\"填写官方模型 ID\" disabled>"
                + "<small>手动型号未核验本 Key 的权限与可用性。</small></p>"
                + "<input type=\"hidden\" name=\"model\" id=\"selected\">"
                + "<button id=\"save\" type=\"submit\" disabled>保存配置</button></form>"
                + "<p><small>模型查询不会保存 Key。确认保存后才写入电视端应用私有存储，"
                + "并关闭这次扫码会话。获取列表不代表每个型号都具有调用权限或额度。</small></p>"
                + "<script>"
                + "var providers=" + providers + ";"
                + "var form=document.getElementById('config'),provider=document.getElementById('provider'),"
                + "key=document.getElementById('key'),base=document.getElementById('base'),"
                + "models=document.getElementById('models'),fetchButton=document.getElementById('fetch'),"
                + "save=document.getElementById('save'),statusText=document.getElementById('status'),"
                + "manualMode=document.getElementById('manualMode'),manual=document.getElementById('manual'),"
                + "manualBox=document.getElementById('manualBox'),selected=document.getElementById('selected');"
                + "var epoch=0,request=null,busy=false,source='';"
                + "function trim(v){return v.replace(/^\\s+|\\s+$/g,'');}"
                + "function choice(){return manualMode.checked?trim(manual.value):models.value;}"
                + "function updateSave(){save.disabled=busy||!trim(key.value)||!choice();}"
                + "function reset(){epoch++;var old=request;request=null;if(old)old.abort();busy=false;source='';"
                + "models.options.length=0;models.add(new Option('请先获取模型列表',''));models.disabled=true;"
                + "manual.value='';selected.value='';manualMode.checked=false;manual.disabled=true;"
                + "manualBox.hidden=true;statusText.textContent='';fetchButton.textContent='获取模型列表';"
                + "fetchButton.disabled=!trim(key.value);base.value=providers[provider.selectedIndex].apiBase;updateSave();}"
                + "for(var i=0;i<providers.length;i++){provider.add(new Option(providers[i].name,providers[i].id));}"
                + "provider.onchange=function(){key.value='';reset();};key.oninput=reset;"
                + "models.onchange=updateSave;manual.oninput=updateSave;"
                + "manualMode.onchange=function(){manualBox.hidden=!manualMode.checked;"
                + "manual.disabled=!manualMode.checked;models.disabled=manualMode.checked||!source;updateSave();};"
                + "fetchButton.onclick=function(){if(busy||!trim(key.value))return;reset();busy=true;"
                + "fetchButton.disabled=true;fetchButton.textContent='获取中…';"
                + "statusText.textContent='正在从提供方查询，请稍候';statusText.style.color='#555';updateSave();"
                + "var stamp=epoch,xhr=new XMLHttpRequest();request=xhr;"
                + "xhr.open('POST',form.action+'/models',true);xhr.timeout=22000;"
                + "xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded;charset=UTF-8');"
                + "xhr.onreadystatechange=function(){if(xhr.readyState!==4||stamp!==epoch||request!==xhr)return;"
                + "request=null;busy=false;fetchButton.disabled=!trim(key.value);fetchButton.textContent='获取模型列表';"
                + "if(xhr.status!==200){statusText.style.color='#b00020';statusText.textContent="
                + "xhr.status===403?'扫码会话已失效，请在电视端重新生成二维码':"
                + "'连接失败或超时，请确认手机与电视在同一局域网，重试或手动输入模型 ID';updateSave();return;}"
                + "try{var result=JSON.parse(xhr.responseText);source=result.source==='error'?'':result.source;"
                + "models.options.length=0;models.add(new Option('请选择模型',''));"
                + "var list=result.models||[];for(var j=0;j<list.length;j++){var item=list[j];"
                + "models.add(new Option(item.name===item.id?item.id:item.name+' ['+item.id+']',item.id));}"
                + "models.disabled=manualMode.checked||!list.length;"
                + "statusText.style.color=result.source==='remote'?'#16703a':'#b06000';"
                + "statusText.textContent=(result.source==='preset'?'官方候选（非实时列表），更新时间 '+result.updatedAt+'\\n':'')"
                + "+result.message;updateSave();}"
                + "catch(error){source='';statusText.style.color='#b00020';"
                + "statusText.textContent='列表响应无法解析，请重试或手动输入模型 ID';updateSave();}};"
                + "xhr.send('provider='+encodeURIComponent(provider.value)+'&apiKey='+encodeURIComponent(trim(key.value)));};"
                + "form.onsubmit=function(event){if(busy||!trim(key.value)||!choice()){event.preventDefault();return false;}"
                + "selected.value=choice();key.value=trim(key.value);save.disabled=true;save.textContent='保存中…';};"
                + "window.onpagehide=function(){epoch++;if(request)request.abort();key.value='';manual.value='';};"
                + "reset();</script></body></html>";
    }
}
